[package]
name = "arithmetic-core"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[lib]
name = "arithmetic_core"
path = "src/lib.rs"

